### ISSUE TITLE
Optional Attributes für Read-More- and Title-Links

### ISSUE THREAD

**Issue by benthebear** [palasthotel/grid#246]
Users ask, wether we could add a Interface to add a target="" Attribute, which raises the Question wether we want to add more of the HTML-Attributes as optional Fields to Links.
Title might be another sensible Attribute.

@EdwardBock @mkernel @SaschaHagemann @greatestview @kroppenstedt Any Opinions on that one?

Heres the demand:
https://github.com/palasthotel/boell/issues/1392

**Comment by EdwardBock** [comment]
@mkernel will create a method in GridAjaxEndpoint that return an empty array. Than we will override this method in grid and drupal for internal search results.

**Comment by mkernel** [comment]
@EdwardBock i think this is the wrong issue for your comment... did you mean #145?

**Comment by EdwardBock** [comment]
@mkernel yes I did :D

**Comment by mkernel** [comment]
Then let's continue over there.

**Comment by mkernel** [comment]
If i see this correctly this issue has ended in a "won't fix" situation. Closing for now.
