### ISSUE TITLE
Build Drupal 8 Port

### ISSUE THREAD

**Issue by mkernel** [palasthotel/grid#290]
As we learned on the 2014 drupalcamp in FFM we have to talk about the d8 port priority, so please discuss: @benthebear, @MarcusAbel, @EdwardBock:

It seems the layouts everywhere module is postponed to 9.x and panels won't be ready for 8.x on launch. Our roadmap currently has the big "more flexible grid support" point which is essentially an idea from @EdwardBock. On the other side we face a huge opportunity if we're ready for d8 early on. 

So, we either team up and let one developer work on the d8 port while the others work on the grid flexibility to get both points done for a 1.0RC. Or we postpone one of the two issues. If so - which one?

**Comment by EdwardBock** [comment]
@mkernel 
You've done that, right? So I'll close this one.
