### ISSUE TITLE
build grid website

### ISSUE THREAD

**Issue by mkernel** [palasthotel/grid#322]
We need a place for the documentation and the packaged plugin/module. After discussion with @MarcusAbel we think it's best suited to be done by @EdwardBock (maybe with help from @kroppenstedt for design/layout).

**Comment by EdwardBock** [comment]
This one is on @annebirga and @JuliaKrischik . You have your own project for this, right?

**Comment by annebirga** [comment]
@EdwardBock Was soll ich hier tun? @JuliaKrischik und ich haben [hie](https://gitlab.palasthotel.de/palasthotel/grid-website/issues)r ein Grid-Marketing-Issue, was allerdings momentan pausiert.

**Comment by EdwardBock** [comment]
@annebirga 

So we can close this issue if you have issues for the grid website elsewhere.
