### ISSUE TITLE
Feature request: Add container-variants-settings?

### ISSUE THREAD

**Issue by SaschaHagemann** [palasthotel/grid#327]
When adding the C-6-6-container (https://github.com/palasthotel/finanzportal/issues/19) by adding a database-entry in grid_container_type, I was wondering if it's a good idea to add the **list of available containers** to `/admin/config/grid/settings` - means: let us (or the site-admin) **config via grid-settings (e.g. simple checkboxes), which containers will be available and which will be not**, so it's easier to add or remove containers (not just at the beginning of a project but also later during a running project).

good or bad idea, @mkernel & @EdwardBock?

**Comment by EdwardBock** [comment]
@SaschaHagemann @mkernel 
Elements trash for Drupal is working
