### ISSUE TITLE
Grid in IE9 compatibility mode

### ISSUE THREAD

**Issue by jdwestermann** [palasthotel/grid#346]
When loading Grid in IE11's compatibility mode for IE9, it stops loading, claiming it doesn't support "tpl_slotstylechanger".

![compatibility](https://cloud.githubusercontent.com/assets/8479525/4183560/22c2d40e-373e-11e4-8073-afcdc0cd4d06.png)

**Comment by EdwardBock** [comment]
Seems to be fixes by accident.
