### ISSUE TITLE
Box templating in plugin/module

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid#364]
@mkernel 
I thought about the templating problem we talked about this week. How about a new method in base grid_box->template_path() that return null and can be overritten in the box implementation. If you define the moduel/plugin path there you could use that in the rendering and you could use same box namings in the new path.

What do yout think @mkernel ?

**Comment by mkernel** [comment]
That's a good idea! However i wouldn't tie it to the box class... another hook would add more flexibility (e.g. modules only providing templates). However: as soon as we add more template paths, we need to ensure that the priority of folders is clear and not "in the way".

**Comment by EdwardBock** [comment]
@mkernel 
Ok that's a point. So how about a hook alter that provides an array with key = boxclass and value = path to template?

**Comment by mkernel** [comment]
As we already discussed in person: the hook should only provide paths to:

* keep the naming conventions stable for template files
* add flexibility, as every module can then provide templates for every grid box

**Comment by EdwardBock** [comment]
It is implemented like you said
Am 31.01.2015 22:47 schrieb "mkernel" <notifications@github.com>:
