### ISSUE TITLE
Preview on old revision opens two tabs

### ISSUE THREAD

**Issue by mkernel** [palasthotel/grid#368]
When previewing an older revision, two tabs are opened: one with the correct revision and one for the current draft.

Seen on: Safari.

**Comment by EdwardBock** [comment]
@mkernel 
My Installation doesn't do that!?! Let's have a closer look next friday

**Comment by EdwardBock** [comment]
Safari does it!

**Comment by EdwardBock** [comment]
@mkernel 
is fixed
