### ISSUE TITLE
box css editmode hook

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid#372]
@mkernel 
is it possible to add another view mode for editor sidebar?

**Comment by EdwardBock** [comment]
@mkernel 
Like we discussed: there is already a solution by providing a custom box css with field widget hook. But we should provide a second hook for adding box css for editmode

**Comment by mkernel** [comment]
so, this issue is for you!

**Comment by mkernel** [comment]
Drupal Version is ready.

**Comment by EdwardBock** [comment]
Works like charme
