### ISSUE TITLE
dynamically extensible grid box parameters

### ISSUE THREAD

**Issue by barooney** [palasthotel/grid#377]
I want to build a grid box, which should be able to dynamically add key-value pairs to the box' configuration.

The use case may be to generate a URL from these parameters, but there may be one or one hundred parameters like so:

http://example.com?param1=val1&param2=val2&param3=val3

Programmatically, I would skip through an array and do some sort of

```
$url = 'http://example.com' . '?';
foreach ($this->content->params as $p) {
    $url .= $p['param'] . = . urlencode($p['value']) . '&';
}
// ...
```

Is there a point one could start to make this feature available?

**Comment by EdwardBock** [comment]
Why would you want to save your $_GET parameters to grid box content? Just use $_GET and sanitize the values before you use them.

**Comment by mkernel** [comment]
Without understanding in detail what you're trying to achieve: You can use the list widget in combination with a textfield or a dropdown widget to get a list of get parameters to analyze.

Try experimenting with the list widget. It lets you allow to do just that.

**Comment by barooney** [comment]
I mean something like this:

![bildschirmfoto 2015-03-16 um 09 53 20](https://cloud.githubusercontent.com/assets/7101151/6663004/565fad00-cbc2-11e4-9b77-402c57014990.png)

This should result in

```
http://example.com/feed?param1=value1&param2=value2
```

**Comment by EdwardBock** [comment]
@barooney have a look at the editor widget type list http://doc.the-grid.ws/dokumentation/entwickler/list/ 
You could give each list item two text inputs (param, value)

**Comment by barooney** [comment]
You are the man! Thanks for pointing into the right direction!
