### ISSUE TITLE
Schema Version error

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid#381]
@mkernel 
If you try to update an old grid without schema table you get an fatal error. @MarcusAbel can tell you about it

https://github.com/palasthotel/grid/blob/master/classes/grid_update.php#L74

The try catch doesn't help. Do you have an idea how to handle that?

**Comment by mkernel** [comment]
@EdwardBock @MarcusAbel wordpress or drupal?

**Comment by EdwardBock** [comment]
@mkernel Wordpress

**Comment by mkernel** [comment]
As far as i know there are no old grids left behind... from that time we were the only grid users and nobody out there should have problems with this bug. So we can:

* fix it on a per-setup base whenever it occurs
* close this issue without fixing bugs.
