### ISSUE TITLE
Little CSS Backend Bug 

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#382]
![bildschirmfoto 2015-04-16 um 12 59 22](https://cloud.githubusercontent.com/assets/2060276/7179471/7a6b914e-e438-11e4-923a-29168d5f6b5b.JPG)

When scrolling down, the labels become visible.

**Comment by EdwardBock** [comment]
@greatestview 
on which grid did you get this?

**Comment by greatestview** [comment]
I saw that on one of our MUSIC DEV sites, seems fixed now. It happened, when the grid "action bar" vertical position was below the position of the wordpress menu. Maybe because the black wordpress sidebar (#adminmenuback) has a z-index of 1, whereas the wordpress menu (#adminmenuwrap) has a z-index of 9990, and .grid-tool-list a z-index fo 90.

**Comment by EdwardBock** [comment]
@greatestview thanks, it is fixed!
