### ISSUE TITLE
single content search results too picky

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#383]
The single-content-search only gives results, if you match excactly the post title.

Example:
Article Title is "Toto: Bassist Mike Parcaro ist tot"

If you type "toto tot", there is no search result.

![bildschirmfoto 2015-04-29 um 16 31 28](https://cloud.githubusercontent.com/assets/2060276/7393306/44f2ccf8-ee8d-11e4-8953-e4f377b98755.JPG)

"toto: tot" instead gives the desired result.

![bildschirmfoto 2015-04-29 um 16 31 22](https://cloud.githubusercontent.com/assets/2060276/7393305/42e76c20-ee8d-11e4-97c4-addf426fe291.JPG)

I would say Grid should not consider special chars and also treat words separated with a hypen as separate words ("grid-box" should be found by "grid box")

**Comment by EdwardBock** [comment]
We will discuss that on our grid power day

**Comment by mkernel** [comment]
this issue needs to be moved to the corresponding cms plugin repository: drupal / wordpress.

**Comment by greatestview** [comment]
Moved: https://github.com/palasthotel/grid-wordpress/issues/86
