### ISSUE TITLE
One operation at a time

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid#386]
We got user feedback that grid got confused because users were editing box positions faster than grid could save changes. So those changes were in conflict with Client and server state.
Solutions:
 1. We block the user interface by placing the loading indicator over the grid with an half transparent background.
 1. We implement an operations queue. but this could be very tricky if users change attributes that are connected like box positions
 1. any other ideas?

@mkernel @benthebear ???

**Comment by benthebear** [comment]
I vote for the First Option!

**Comment by EdwardBock** [comment]
@benthebear @mkernel 
First option it is! Looks pretty nice :)
