### ISSUE TITLE
Support-Anfrage: Uncaught TypeError: Cannot read property 'container' of undefined

### ISSUE THREAD

**Issue by SaschaHagemann** [palasthotel/grid#388]
Ronen Gol <ronengol@gmail.com> 

----------

Hello guys,

I'm using your Grid plugin on Wordpress(V-4.2.2) and must say you did a great job! :)

Unfortunately, when I try to use it with Polylang for multi language support there is some kind of a conflict that prevents 'The Grid' section from loading in the admin section of a post/page. It just keeps showing the loading animation.

When I go to the javascript console I get the following error: 

Uncaught TypeError: Cannot read property 'container' of undefined
GridAjax.success_fn @ GridSync.js?ver=4.2.2:103
settings.success @ GridSync.js?ver=4.2.2:55
v.Callbacks.l @ jquery-1.8.3.min.js?ver=4.2.2:2
v.Callbacks.c.fireWith @ jquery-1.8.3.min.js?ver=4.2.2:2
T @ jquery-1.8.3.min.js?ver=4.2.2:2
v.support.ajax.v.ajaxTransport.send.r @ jquery-1.8.3.min.js?ver=4.2.2:2

Do you guys happen to have any advice on how to avoid this conflict, or another language plugin I could use?

Thanks!!
Ronen

**Comment by SaschaHagemann** [comment]
apache php error log:

>> [26-May-2015 17:20:07 UTC] PHP Notice:  Trying to get property of non-object in /.../wp-content/plugins/grid/lib/classes/grid_db.php on line 594

**Comment by EdwardBock** [comment]
Thanks @SaschaHagemann 
would you like to have a look at this @mkernel ?
Thanks :)

**Comment by mkernel** [comment]
Just fixed it on master branch. Assigning @EdwardBock to inform the user once a wordpress update is published.

**Comment by EdwardBock** [comment]
@mkernel @SaschaHagemann 
Update was released
