### ISSUE TITLE
Recent Articles suggestion in Single Contents Box

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#390]
In our current project (despite being very happy with Grid) the users have two suggestions for a better workflow. Maybe they are already on your roadmap:
1. A locking mechanism, so that its not possible to work simultaneously on the same grid.
2. In our current project, the workflow is: Writing an article, go to Grid, select Box -> Single Contents, search for that article title. It would be an improvement if there is already a list with the recent created articles, from where you can pick one.

**Comment by EdwardBock** [comment]
@greatestview 
1. is in work with our grid nodejs service
2. will be available with next grid update

**Comment by greatestview** [comment]
@EdwardBock, I cannot find the second feature in the current Grid version. Is it already there?

**Comment by EdwardBock** [comment]
@greatestview 

Yes it is. If you open the boxes type "Content" you'll get recent contents. Please check again.

**Comment by greatestview** [comment]
Thats been a while now :) But you‘re right. Back to you for 1. the locking mechanism.

**Comment by mkernel** [comment]
@greatestview the locking mechanism is already implemented and in place. contact one of us for helping you enabling it for the customer.
