### ISSUE TITLE
Allow Video Box Template

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#393]
Currently it´s not possible to manipulate the Video Box via a template, because the video logic is hardcoded. Could you be so kind and rewrite the video box plugin so that templates are possible? Thanxx

**Comment by mkernel** [comment]
The Video Box is using oembed and by design fetches HTML directly from the specific video network.
It's hard to add flexibility without knowing what you're trying to achieve in the first place.

**Comment by greatestview** [comment]
It would be great to make the oembed html code accessible in a php variable, so that its possible to build a custom wrapper html wrapper around that. I think there is no need to manipulate the video code itself.

A separate template example:

```
<div class="grid-box grid-box-video …">
  <!-- grid-box-before -->
  <div class="grid-box-video-wrapper">
    <?php echo $content; // here goes the oembed video code ?>
  </div>
  <!-- grid-box-after -->
</div>

**Comment by mkernel** [comment]
I'm pretty sure i'm not getting the point here... to ensure we're not talking about a bug i created a template file grid-box-video.tpl.php and pasted your code into it. It works. The HTML is already in $content. Everything looks fine and works as expected.

**Comment by EdwardBock** [comment]
@greatestview 
So I'm assigned but not really sure what to do :D Like @mkernel said it is already possible to use the template you want @greatestview . If not let's talk in person. Perhaps I didn't get what you want either.

**Comment by greatestview** [comment]
Seems like it is already possible to use a separate template file for the video box (grid-box-video.tpl.php). Thats fine and perfect!
