### ISSUE TITLE
Grid locking not working reliable

### ISSUE THREAD

**Issue by mkernel** [palasthotel/grid#394]
We have encountered multiple situations in which the multiple-user-locking is not working reliable.
One Problem we're facing: local development. Everyone working on "localhost" is essentially on the same domain. We should rethink our keying mechanism.

And it seems that the locking is not detecting closed sessions fast enough / not detecting them at all.
We need a more robust testing setup: multiple OSes, multiple Browser Versions.

**Comment by mkernel** [comment]
cc @JanaME

**Comment by EdwardBock** [comment]
@mkernel 
How about an ping mechanism? The server sends an ping every x seconds and if the user is not answering the user on server side will be deleted.

The key hmmm ....

**Comment by mkernel** [comment]
Adding a ping mechanism would be good. 

Concerning the key: in addition to the path we could add a "sync key" to the settings page.

**Comment by EdwardBock** [comment]
@mkernel 
Would you take care of the ping mechanism on server side? I made an Issue in the project...

**Comment by mkernel** [comment]
I did add/fix ping, optimized the look (a little bit) and added a multiple-tabs-detection. So please publish a grid update and we need to update our grid async service.

**Comment by EdwardBock** [comment]
Looks very good! Thanks @mkernel
