### ISSUE TITLE
Grid vs. Gitter vs. Raster

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#397]
Just stumbled across this:

<img width="774" alt="bildschirmfoto 2016-01-11 um 10 49 11" src="https://cloud.githubusercontent.com/assets/2060276/12230459/08f27bfc-b851-11e5-8ed7-ff9a4cb00f72.png">

I was confused, because the product was named »Grid« before. Or sometimes »Raster«. In this screenshot it´s even worse, because there are two product names in the header. Is the official plugin name Grid or Gitter? Is Gitter a German word or a fictional English word (rhetorical question, I know your intention :) )?

My option on this: We should not try and translate the product name into different languages, Grid is just Grid. Makes life easier and users *and* Google won´t get confused about our product name.

**Comment by EdwardBock** [comment]
@greatestview 
Yep that's noting new. I already started to retranslate it. 
https://github.com/palasthotel/grid-wordpress/issues/65

**Comment by EdwardBock** [comment]
But thanks anyway :)

**Comment by greatestview** [comment]
Purrrfect

**Comment by greatestview** [comment]
I´ve just seen that this is still an issue, so I reopen this one :)

**Comment by EdwardBock** [comment]
<img width="792" alt="bildschirmfoto 2016-04-22 um 14 01 33" src="https://cloud.githubusercontent.com/assets/3862417/14740907/beac7cea-0892-11e6-8879-70acda0957f6.png">

We got through the waiting line. Its Grid everywhere now
