### ISSUE TITLE
multi-byte safe PHP string commands

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#400]
We just had a strange bug on a customer site caused by a non-multi-byte-safe PHP string command in the theme (substr). It had nothing to do with Grid, but when I searched for similar commands in the Grid plugin code, I think I found some lines, where those unsafe commands are used, e.g. strpos, strlen or substr.

Here is a list with all those unsafe commands, which should be replaced, if they deal with UTF-8 user input, e.g. Prolog, Epilog, Title and such stuff:
http://php.net/manual/de/ref.mbstring.php

**Comment by mkernel** [comment]
I checked those methods and they're only used on machine-strings (certain grid ids with string prefixes, hex color values, path names) and those should work fine. Especially the dangerous substr() method is used to kill a prefix (which is calculated using strlen of another string which is the prefix of the first one), so this is consistent and should be fine, too. 

I think: nothing to do here, move along.

**Comment by greatestview** [comment]
Sänk ju!
