### ISSUE TITLE
Test WP 4.5 

### ISSUE THREAD

**Issue by kroppenstedt** [palasthotel/grid#402]
@EdwardBock 
```Developers, please test your plugins and themes against WordPress 4.5 and update your plugin’s Tested up to version in the readme to 4.5 before next week. If you find compatibility problems, we never want to break things, so please be sure to post to the support forums so we can figure those out before the final release. ```
https://wordpress.org/news/2016/03/wordpress-4-5-release-candidate/

**Comment by EdwardBock** [comment]
Works!
