### ISSUE TITLE
User lock timeout

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid#403]
@mkernel 
We have a Problem with the async service if someone leaves the browser open because nobody else can use that grid from that moment. We need a timeout if a user has stopped working on a grid than loses the locking right.

**Comment by mkernel** [comment]
@EdwardBock i implemented the following logic: if the user is idle for 10 minutes AND there are multiple users on the same grid AND the user is the one having write access: perform a force browser reload. This is the easiest way to handover the lock to another user. 
Have a look.

**Comment by EdwardBock** [comment]
We found an issue with if the system throttles the browser. Bugfix is timestamp that fixes time differences.

**Comment by EdwardBock** [comment]
@mkernel 
Is working now. But I set the timeout for 5 minutes. 10 seems pretty long. Perhaps even 5 are to long. We should make this configuratable. New issue for this.
