### ISSUE TITLE
Add RSS Box to Core

### ISSUE THREAD

**Issue by benthebear** [palasthotel/grid#408]
I would love to see an RSS-Box in Core. @EdwardBock

**Comment by EdwardBock** [comment]
@benthebear 
It is now! 

Class:
https://github.com/palasthotel/grid/blob/master/classes/grid_rss_box.php

And there are templates which you can overwrite if needed:
https://github.com/palasthotel/grid/blob/master/templates/frontend/grid-box-rss.tpl.php
https://github.com/palasthotel/grid/blob/master/templates/frontend/grid-box-rss-editmode.tpl.php
