### ISSUE TITLE
Plaintext Box für Grid?

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid#409]
@mkernel @benthebear 
What about a plaintext box for grid core boxes? We got several issues where someone needed to place JS Snippets. They tried to put in into the HTML box but than the JS will be interpreted in the backend grid too. The solution is always to program a plaintext box.

Pros and cons for core plaintext box:

-Security issues? 
+Never program a plaintext box for a single projekt again

**Comment by benthebear** [comment]
+1

**Comment by EdwardBock** [comment]
We have it with the now
