### ISSUE TITLE
Bug in rss-box template

### ISSUE THREAD

**Issue by JuliaKrischik** [palasthotel/grid#417]
@EdwardBock I discovered a  bug in the template file of the grid-rss-box. [Here](https://github.com/palasthotel/grid/blob/master/templates/frontend/grid-box-rss.tpl.php#L32) you find a call on the var_dump-function, that makes the rss data array visible in the frontend.

Could you please fix that?:)

**Comment by EdwardBock** [comment]
YEP!

**Comment by EdwardBock** [comment]
It is fixed. Thanks!

**Comment by EdwardBock** [comment]
Ah no better: get the recent grid update and test it please. if it is working you can close this issue :)

**Comment by JuliaKrischik** [comment]
It's working fine, thanks!
