### ISSUE TITLE
Bug after updating SG GT Grid to Version 1.6.7 

### ISSUE THREAD

**Issue by MarcusAbel** [palasthotel/grid#419]
Fatal error: Cannot redeclare class grid_plaintext_box in /kunden/110227_33607/kunden/staedtisches_gymnasium_wordpress/wp-content/plugins/grid_boxes/grid_plaintext_box.inc on line 38

Any idea - I have restored WordpressPlugin and Database, hoping the fatals on all landingpages are  away for today ...

**Comment by MarcusAbel** [comment]
Donnerstag mal bitte mit mir draufgucken lieber @EdwardBock ...

**Comment by EdwardBock** [comment]
@MarcusAbel You know how to fix it now ;)

**Comment by MarcusAbel** [comment]
Got it!
