### ISSUE TITLE
Backend Cache or What?!

### ISSUE THREAD

**Issue by MarcusAbel** [palasthotel/grid#425]
Hi @EdwardBock 

Just talked to you about problems in my backend mask using a two step configuration mask at my new gridbox.

https://github.com/palasthotel/emma/blob/d0ccc38905416b3cabe0841e5550f0c0568dbe5a/docroot/sites/all/modules/custom/emma_lesesaal/emma_lesesaal_grid_image_teaser_box.inc

1st step is: insert query
2nd step should be: select results (this is possible in livetime but after cleaning cache and browser refreshes 'til doctor comes ...)

**Comment by EdwardBock** [comment]
Its no bug. Just corrupt json output.
