### ISSUE TITLE
Autossuggest not working

### ISSUE THREAD

**Issue by JuliaKrischik** [palasthotel/grid#427]
Hi @EdwardBock,

i found out that autocomplete has a bug. It occurred when I placed a custom list-box and gave it a tag as filter. When a I wanted to edit it again, i could not open it again - just the gray background appeared.

JS-Console said:
`autocomplete.js?ver=4.6.1:39` Uncaught TypeError: Cannot read property '$el' of undefined(…)`and `Uncaught TypeError: jQuery(...).suggest is not a function(…)`.

@mkernel did a hotfix [here](https://gitlab.palasthotel.de/palasthotel/wid/commit/59d13622faf03bd1f3139fb782e40493c67eeaca).

**Comment by EdwardBock** [comment]
Thanks @JuliaKrischik and @mkernel ! Fixed it is too. Update will be coming soon.
