### ISSUE TITLE
RSS-Box-Item: Add getter for raw

### ISSUE THREAD

**Issue by JanaME** [palasthotel/grid#432]
Hey @EdwardBock 

I needed a feed image in my rss box template and wasn’t able to get it, because the property `raw`, which is the SimplePie Object is defined private.

So I added a get-method for it in my patch. Can you add the following lines to core at https://github.com/palasthotel/grid/blob/master/classes/grid_rss_box.php#L139 please

```php
public function getRaw() {
	return $this->raw;
}
```

**Comment by EdwardBock** [comment]
Added this to next Update. Thanks!
