### ISSUE TITLE
Apostrophe ' destroys title in custom edit template

### ISSUE THREAD

**Issue by StefanBoettcherASMB** [palasthotel/grid#434]
![bildschirmfoto 2017-04-19 um 15 06 18](https://cloud.githubusercontent.com/assets/15629627/25181536/2ebfbdfc-2512-11e7-8f8b-b549971d2ce8.jpg)

![bildschirmfoto 2017-04-19 um 15 06 27](https://cloud.githubusercontent.com/assets/15629627/25181553/3778e1a8-2512-11e7-9ba7-b711203a26f4.jpg)

on save the new box title is now cut

possible fix (encode ' client-side): https://github.com/palasthotel/musiktitel/commit/49dba7dd1e496899394af8e174de698127d7564a

**Comment by EdwardBock** [comment]
@StefanBoettcherASMB 

Thanks for the fix!
