### ISSUE TITLE
Feature: Duplicate Box

### ISSUE THREAD

**Issue by StefanBoettcherASMB** [palasthotel/grid#435]
It would be very helpful I one could duplicate a box with all settings etc. Right now you have to re-configure every box which can be time consuming.

**Comment by StefanBoettcherASMB** [comment]
ping xD

**Comment by EdwardBock** [comment]
Since you are not the first one asking for this... new prio.

**Comment by EdwardBock** [comment]
@StefanBoettcherASMB

I've implemented this featu9re for 1.8.2 grid release. Let's check tomorrow if ux is working @kroppenstedt

**Comment by EdwardBock** [comment]
- [ ] JS Bug where drag and drop duplicates but adds a ghost box too

- [ ] alt key press turns delete box to duplicate box

- [ ] visual highlight duplicate for some seconds

**Comment by EdwardBock** [comment]
@StefanBoettcherASMB @JuliaKrischik @kroppenstedt 

Works with Grid Version 1.8.2
