### ISSUE TITLE
PHP7 Warning

### ISSUE THREAD

**Issue by fym** [palasthotel/grid#436]
`Warning: Parameter 2 to grid_plugin\boxes::posts_where() expected to be a reference, value given in /[…]/wordpress/wp-includes/class-wp-hook.php on line 298`

- fresh WP Install (4.8)
- PHP 7.1.1

**Comment by fym** [comment]
@EdwardBock 

Scheint am pass by reference in `Line 53: /grid/classes/boxes.inc´ zu liegen. Warning verschwindet, wenn die Variable direkt übergeben wird.

**Comment by EdwardBock** [comment]
@fym 

Thanks! Is fixed
