### ISSUE TITLE
Hooking into Boxes

### ISSUE THREAD

**Issue by benthebear** [palasthotel/grid#444]
It's the second time, that customers want additions to an existing Core-Box (after it's been in use), so that I think about wether it's a good Idea to add hooks to the content_structure and / or the rendering Methods of the Base-Boxes, so that we can add Fields and Render behavior of existing core Boxes without hacking core.

@EdwardBock @mkernel to be discussed.

**Comment by mkernel** [comment]
you might be able to achieve just that by subclassing and hiding the base class. There are hooks for that already.

**Comment by benthebear** [comment]
What are you doing here?! It's Friday Night! 💃

**Comment by mkernel** [comment]
So.. who did start this? me or you?

**Comment by EdwardBock** [comment]
We had several projects where we did it with subclass and hiding the original one. That's working but we always have complains about already placed boxes that need to be replaced then. I don't know if hooks are the solution!?

**Comment by EdwardBock** [comment]
After discussion with @mkernel this is a won't fix.

@benthebear 
There are solutions for this problem with subclassing.
