### ISSUE TITLE
Fatal error on activation, fresh installation

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#461]
When trying to activate Grid v2.1.4 via backend on a fresh WordPress 5.6 installation with no other plugins and PHP 7.3, I get this error:

> Fatal error: Uncaught Error: Call to undefined method Palasthotel\Grid\API::getDatabaseSchema() in /…/wp-content/plugins/grid/wordpress_plugin.php:450 Stack trace: #0 /…/wp-includes/class-wp-hook.php(287): Palasthotel\Grid\WordPress\Plugin->activate('') #1 /…/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /…/docroot/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #3 /…/docroot/wp-admin/plugins.php(193): do_action('activate_grid/w...') #4 {main} thrown in /…/docroot/wp-content/plugins/grid/wordpress_plugin.php on line 450

Activation is not possible. Any ideas @EdwardBock?

**Comment by EdwardBock** [comment]
Hi @greatestview 

There was a refactoring typo bug. Have a look at the 2.1.5 release. It should be fixed.

**Comment by greatestview** [comment]
Works like a charm, thank you!
