### ISSUE TITLE
Error: Undefined constant

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#462]
After updating Grid in a project from v1.8.6 to v2.1.4, I receive this error on the WordPress update page:

> [18-Dec-2020 13:21:19 UTC] PHP Fatal error:  Uncaught Error: Undefined constant 'Grid\Constants\GRID_CSS_VARIANT_TABLE' in /…/wp-content/plugins/grid/classes/Update.php:36
> Stack trace:
> #0 /…/wp-content/plugins/grid/lib/grid/classes/UpdateBase.php(39): Palasthotel\Grid\WordPress\Update->update_2()
> #1 /…/wp-content/plugins/grid/wordpress_plugin.php(579): Palasthotel\Grid\UpdateBase->performUpdates()
> #2 /…/wp-content/plugins/grid/wordpress_plugin.php(217): Palasthotel\Grid\WordPress\Plugin->update()
> #3 /…/wp-includes/class-wp-hook.php(287): Palasthotel\Grid\WordPress\Plugin->init('')
> #4 /…/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #5 /…/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #6 /…/wp-settings.php(546): do_action('init')
>  in /…/wp-content/plugins/grid/classes/Update.php on line 36

I looked through the code but have no suggestion so far. Any ideas @EdwardBock?

**Comment by EdwardBock** [comment]
This was an autoloader problem which is fixed with version 2.1.6 . Please try another update.

**Comment by greatestview** [comment]
Works like a charm, thank you!
